name: Build

on:
 push:
    branches: [ master ]
 workflow_dispatch:

jobs:
 build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --noconfirm --onedir --windowed --add-data "./nessie.ico;./" "./apexpresence.py"
      
    - name: Increment version and create release
      id: version_increment
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: '0.01'
        pre_release: true
        files: './dist/apexpresence.exe'
